# Generated by Django 3.2.6 on 2021-09-03 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='school_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_name', to='demo.school'),
        ),
        migrations.AlterField(
            model_name='route',
            name='stops',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
